name: iOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-${{ runner.os }}-

      - name: Resolve Packages
        run: xcodebuild -resolvePackageDependencies -project VoltConnect.xcodeproj -scheme VoltConnect

      - name: Build (Debug)
        run: |
          xcodebuild \
            -project VoltConnect.xcodeproj \
            -scheme VoltConnect \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -quiet \
            build

      - name: Test (Debug)
        run: |
          if xcodebuild -list -project VoltConnect.xcodeproj | grep -q "VoltConnectTests"; then
            xcodebuild \
              -project VoltConnect.xcodeproj \
              -scheme VoltConnect \
              -configuration Debug \
              -destination 'platform=iOS Simulator,name=iPhone 15' \
              -quiet \
              test
          else
            echo "No tests target found; skipping."
          fi
